// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Threading.Tasks;

namespace AstroWall
{
    public partial class FreshInstallViewController : NSView
    {
        private Func<Task> callback;

        public FreshInstallViewController(IntPtr handle) : base(handle)
        {
        }

        partial void saveAction(Foundation.NSObject sender)
        {
            this.Window.Close();
            if (callback == null) throw new Exception("Callback not registered");
            callback();
        }

        public void regSaveCallback(Func<Task> callbackArg)
        {
            this.callback = callbackArg;
        }

        public void runCallback()
        {
            if (callback == null) throw new Exception("Callback not registered");
            callback();
        }
    }
}
