// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AstroWall
{
    public partial class AboutViewController : NSViewController
    {


        public AboutViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            OutletVersion.StringValue = General.currentVersion();
        }

        // Not feasible to make static bc of partial class
#pragma warning disable CA1822
        partial void ActionGithub(NSObject sender)
        {
            General.Open("https://github.com/wiegell/AstroWall/");
        }
        partial void ActionWeb(NSObject sender)
        {
            General.Open("https://wiegell.github.io/AstroWall/");
        }
        partial void ActionIssues(NSObject sender)
        {
            General.Open("https://github.com/wiegell/AstroWall/issues");
        }
#pragma warning restore


    }
}
