// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;

namespace AstroWall
{
    /// <summary>
    /// View controller for about window.
    /// </summary>
    public partial class AboutViewController : NSViewController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AboutViewController"/> class.
        /// Xcode default constructor.
        /// </summary>
        /// <param name="handle"></param>
        public AboutViewController(IntPtr handle)
            : base(handle)
        {
        }

        /// <summary>
        /// View did load lifecycle hook. Used to set values in view.
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            OutletVersion.StringValue = General.CurrentVersionLongWithCommit();
        }

        // Not feasible to make static bc of partial class
        #pragma warning disable CA1822

        /// <summary>
        /// Opens github repo in defult browser.
        /// </summary>
        partial void ActionGithub(NSObject sender)
        {
            General.Open("https://github.com/wiegell/AstroWall/");
        }

        /// <summary>
        /// Opens public web page in default browser.
        /// </summary>
        partial void ActionWeb(NSObject sender)
        {
            General.Open("https://wiegell.github.io/AstroWall/");
        }

        /// <summary>
        /// Opens gh issues page in default browser.
        /// </summary>
        /// <param name="sender"></param>
        partial void ActionIssues(NSObject sender)
        {
            General.Open("https://github.com/wiegell/AstroWall/issues");
        }
        #pragma warning restore

    }
}
