// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Threading.Tasks;
using AstroWall.BusinessLayer.Preferences;

namespace AstroWall
{
    public partial class FreshInstallViewController : NSView
    {
        private Func<Preferences, Task> callback;

        public FreshInstallViewController(IntPtr handle) : base(handle)
        {
        }

        partial void saveAction(Foundation.NSObject sender)
        {
            this.Window.Close();
            if (callback == null) throw new InvalidOperationException("Callback not registered");
            var prefs = createPrefs();
            callback(prefs);
        }

        public void regSaveCallback(Func<Preferences, Task> callbackArg)
        {
            this.callback = callbackArg;
        }

        /// <summary>
        /// To be used if install location is not correct
        /// </summary>
        public void DisableUpdatesOptions()
        {
            this.OutletAutoinstall.Enabled = false;
            this.OutletCheckUpdatesAtStartup.Enabled = false;
            this.OutletAutoinstall.State = NSCellStateValue.Off;
            this.OutletCheckUpdatesAtStartup.State = NSCellStateValue.Off;
        }

        private Preferences createPrefs()
        {
            var prefs = new Preferences();
            prefs.AutoInstallUpdates = (this.OutletAutoinstall.State == NSCellStateValue.On);
            prefs.
            CheckUpdatesOnStartup = (this.OutletCheckUpdatesAtStartup.State == NSCellStateValue.On);
            prefs.RunAtStartup = (this.OutletRunAtStartup.State == NSCellStateValue.On);


            return prefs;
        }

        public void runCallback()
        {
            if (callback == null) throw new InvalidOperationException("Callback not registered");
            callback(createPrefs());
        }

        partial void ActionCheckUpdatesAtStartup(NSObject sender)
        {
            if (OutletCheckUpdatesAtStartup.State == NSCellStateValue.Off)
            {
                OutletAutoinstall.State = NSCellStateValue.Off;
                OutletAutoinstall.Enabled = false;
            }
            else
            {
                OutletAutoinstall.State = NSCellStateValue.On;
                OutletAutoinstall.Enabled = true;
            }
        }
    }
}
