// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AstroWall
{
	public partial class PostProcessContentViewController : NSView
	{
		public PostProcessContentViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
