// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using AstroWall.BusinessLayer.Preferences;
using Foundation;

namespace AstroWall
{
    /// <summary>
    /// Subview of post processing window to set text settings.
    /// </summary>
    public partial class PostProcessTextSettings : NSView
    {
        private Action<AddTextPreference> changePrefsCallback;
        private AddTextPreference addText;

        /// <summary>
        /// Initializes a new instance of the <see cref="PostProcessTextSettings"/> class.
        /// </summary>
        /// <param name="handle"></param>
        public PostProcessTextSettings(IntPtr handle)
            : base(handle)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostProcessTextSettings"/> class.
        /// </summary>
        public PostProcessTextSettings()
            : base()
        {
        }

        /// <summary>
        /// Sets post process settings to gui.
        /// </summary>
        /// <param name="at"></param>
        internal void SetData(AddTextPreference at)
        {
            if (at != null)
            {
                addText = at;
                OutletEnabled.State = at.IsEnabled ? NSCellStateValue.On : NSCellStateValue.Off;
            }
        }

        /// <summary>
        /// Register callback on save.
        /// </summary>
        /// <param name="ac">Callback / delegate that takes an AddText instance as argument.</param>
        internal void RegChangePrefsCallback(Action<AddTextPreference> ac)
        {
            changePrefsCallback = ac;
        }

        /// <summary>
        /// Get bool from outlet.
        /// </summary>
        /// <param name="sender"></param>
        private static bool GetCheckmarkBoolFromOutlet(NSButton sender)
        {
            return sender.State == NSCellStateValue.On;
        }

        /// <summary>
        /// Save action.
        /// </summary>
        /// <exception cref="InvalidOperationException">Throws if no callback set.</exception>
        partial void ActionSave(NSObject sender)
        {
            if (changePrefsCallback == null)
            {
                throw new InvalidOperationException("callback not defined");
            }
            else if (addText == null)
            {
                throw new InvalidOperationException("old AddText not defined");
            }
            else
            {
                bool newStateOfEnabled = GetCheckmarkBoolFromOutlet(this.OutletEnabled);
                Console.WriteLine("Registering new state from view: " + newStateOfEnabled);
                changePrefsCallback(new AddTextPreference(addText, newStateOfEnabled));
                this.Window.Close();
            }
        }
    }
}
