// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using AstroWall.BusinessLayer.Preferences;

namespace AstroWall
{
    public partial class PostProcessTextSettings : NSView
    {
        Action<AddText> changePrefsCallback;
        AddText addText;

        public PostProcessTextSettings(IntPtr handle) : base(handle)
        {
        }
        public PostProcessTextSettings() : base()
        {
        }

        public void setData(AddText at)
        {
            if (at != null)
            {
                addText = at;
                OutletEnabled.State = at.isEnabled ? NSCellStateValue.On : NSCellStateValue.Off;
            }
        }

        public void regChangePrefsCallback(Action<AddText> ac)
        {
            changePrefsCallback = ac;
        }

        partial void ActionEnabled(NSObject sender)
        {
            if (changePrefsCallback == null)
                throw new Exception("callback not defined");
            else if (addText == null)
                throw new Exception("old AddText not defined");
            else
            {
                bool newStateOfEnabled = getCheckmarkBoolFromSender(sender);
                Console.WriteLine("Registering new state from view: " + newStateOfEnabled);
                changePrefsCallback(new AddText(addText, newStateOfEnabled));
                //OutletEnabled.State = newStateOfEnabled ? NSCellStateValue.On : NSCellStateValue.Off;
            }
        }

        private bool getCheckmarkBoolFromSender(NSObject sender)
        {
            return ((NSButton)sender).State == NSCellStateValue.On;
        }
    }
}
