// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Threading.Tasks;

namespace AstroWall
{
    public partial class FreshInstallViewController : NSView
    {
        private Func<BusinessLayer.Preferences, Task> callback;

        public FreshInstallViewController(IntPtr handle) : base(handle)
        {
        }

        partial void saveAction(Foundation.NSObject sender)
        {
            this.Window.Close();
            if (callback == null) throw new Exception("Callback not registered");
            var prefs = createPrefs();
            callback(prefs);
        }

        public void regSaveCallback(Func<BusinessLayer.Preferences, Task> callbackArg)
        {
            this.callback = callbackArg;
        }

        private BusinessLayer.Preferences createPrefs()
        {
            var prefs = new BusinessLayer.Preferences();
            prefs.autoInstallUpdates = (this.OutletAutoinstall.State == NSCellStateValue.On);
            prefs.
            checkUpdatesOnLogin = (this.checkupdatesatlogin.State == NSCellStateValue.On);
            prefs.runAtLogin = (this.runatlogin.State == NSCellStateValue.On);


            return prefs;
        }

        public void runCallback()
        {
            if (callback == null) throw new Exception("Callback not registered");
            callback(createPrefs());
        }
    }
}
