// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace AstroWall
{
    public partial class UpdaterPrompViewController : NSView
    {
        private Action<BusinessLayer.UpdatePromptResponse> choiceCallback;
        private string ver;

        public UpdaterPrompViewController(IntPtr handle) : base(handle)
        {
        }

        public void SetRelease(UpdateLibrary.Release rel)
        {
            OutletDescription.StringValue = rel.Description;
            OutletVersion.StringValue = rel.version;
            ver = rel.version;
        }

        public void RegChoiceCallback(Action<BusinessLayer.UpdatePromptResponse> callback)
        {
            choiceCallback = callback;
        }

        partial void ActionInstall(NSObject sender)
        {
            var callRet = new BusinessLayer.UpdatePromptResponse()
            {
                acceptOrSkipUpdate = true,
            };
            choiceCallback(callRet);
        }

        partial void ActionSkip(NSObject sender)
        {
            var callRet = new BusinessLayer.UpdatePromptResponse()
            {
                acceptOrSkipUpdate = false,
                skippedVersion = ver
            };
            choiceCallback(callRet);
        }
    }
}
